module.exports = [{
    "_id": "611977d56d34ab001467911d",
    "firstname": "Admin",
    "lastname": "Admin",
    "email": "admin@gmail.com",
    "password": "admin_pw",
    "address": "NY",
    "active": true
}, {
  "_id": "611b0928fc13ae48fd000005",
  "firstname": "Mai",
  "lastname": "Stych",
  "email": "estych0@cocolog-nifty.com",
  "password": "Khaki",
  "address": "Voronkov",
  "active": true
}, {
  "_id": "611b0928fc13ae48fd000006",
  "firstname": "Naelle",
  "lastname": "de Broke",
  "email": "sdebroke1@mediafire.com",
  "password": "Aquamarine",
  "address": "Langtang",
  "active": false
}, {
  "_id": "611b0928fc13ae48fd000007",
  "firstname": "Andrée",
  "lastname": "Sherlock",
  "email": "bsherlock2@admin.ch",
  "password": "Violet",
  "address": "Jiangwakou",
  "active": false
}, {
  "_id": "611b0928fc13ae48fd000008",
  "firstname": "Valérie",
  "lastname": "Wooller",
  "email": "swooller3@is.gd",
  "password": "Mauv",
  "address": "Wolbrom",
  "active": true
}]